# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-30 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('default_address', models.BooleanField(default=False, verbose_name='默认收货地址')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否删除')),
                ('postcode', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('tag', models.CharField(default=None, max_length=10, verbose_name='标签')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'address',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.UserProfile', verbose_name='用户id'),
        ),
    ]
